### ISSUE TITLE
firefox ns_binding_aborted error

### ISSUE THREAD

**Issue by gamebeaker** [dravorle/Naver2Proxer#3]
try to view: https://proxer.me/chapter/42765/132/en
In firefox 131.0.3 (64-bit) i am unable to view it.
The Network requests look like that:
![grafik](https://github.com/user-attachments/assets/3b91ecb3-5482-4808-9298-98cde42f3f42)
If i try to open the links it shows "Referral Denied"
![grafik](https://github.com/user-attachments/assets/8442ac63-fc61-4484-91f2-58040dd6ead8)

**Comment by dravorle** [comment]
The errors shown are not related to the actual images for the pages but stuff from the website around it. Those fail during load but are generally irrelevant.

Firefox did however not find 2 scripts required to run the main script as of the last tampermonkey update.
That was fixed in https://github.com/dravorle/Naver2Proxer/commit/412e29fbe9e6c0d4b36a2269749274b75d5a763a.

Please update and check! :)

**Comment by gamebeaker** [comment]
@dravorle works like a charm.
